### ISSUE TITLE
BUG: Italics font

### ISSUE THREAD

**Issue by ghost** [amarillonmc/MSE201_w_ygos10#1]

**Comment by amarillonmc** [comment]
It's definitely related to how the newer code handles the Justified Italic texts and definitely fixable.
But I'm not sure where is the problem and some trial/error is expected when I'm fixing this stuff.
Nevertheless, This is one of the things I'm working on.

**Comment by Hello23-Ygopro** [comment]
Okay, thanks.

The only other major bug I've experienced is related to `content_width`...
Have you ever had any problems using `content_width` in 2.0.1? I've had some instances where it distorted my text, but only until I refreshed the set, which also doesn't happen to me at all using 2.0.0.

**Comment by amarillonmc** [comment]
The only thing I know about that is that some parsing of those seems to be different between versions. Since personally, I've never run into serious problems regarding them in this template, I didn't bother to fix all of them, (while I fixed all the serious ones.) But if you have doubt on how a specific property or function is getting parsed from the style script, check out the other MTG templates, they're updated by the original authors of MSE and should support 2.0.1 100%, and then apply them from there.

**Comment by Hello23-Ygopro** [comment]
I'll just add this question here.

The left and right bracket code [here](https://github.com/amarillonmc/MSE201_w_ygos10/blob/master/data/yugioh-series10.mse-style/style#L931) is uncommented. I was wondering if there's a way I can move the brackets upwards so they can be better aligned with the monster type? They seem to be synchronized with the monster type, so if I move it upwards, then the brackets move too.

![labyrinth wall](https://user-images.githubusercontent.com/18324297/39496913-f7cc51bc-4da0-11e8-9c63-6bde122eeccd.png)

**Comment by amarillonmc** [comment]
Try editing ``leftbracket.png`` and ``rightbracket.png``?

I commented those out to fix a bug that the auto-brackets sometimes would not parse right on S/T cards.

**Comment by Hello23-Ygopro** [comment]
> Try editing leftbracket.png and rightbracket.png

I don't know if I want to do that, because let's say I want one particular card to have a different monster type size than another, then I want its left and right brackets to also be different sizes, and I don't want to have multiple bracket .png images for different sizes.

It looks like the code for the brackets are [here](https://github.com/amarillonmc/MSE201_w_ygos10/blob/master/data/yugioh.mse-game/card_fields#L334)?

I wonder if I should change my fields from `type: choice` to this instead:
```
extra card field:
	type: text
	name: leftbracket
	default: "["
	editable: false
extra card field:
	type: text
	name: rightbracket
	default: "]"
	editable: false
```
With these new settings I wouldn't have to rely on the images, the brackets look better as text in my opinion, it's easier to change their size, and the monster type size won't change at the same time, but I'm not sure how well it will work on 2.0.1.

> I commented those out to fix a bug that the auto-brackets sometimes would not parse right on S/T cards.

What about using [these](https://github.com/247321453/MagicSetEditor2/tree/master/data/yugioh-standard-levels.mse-symbol-font/enmark) images for Spell and Trap Cards? In my opinion, they look much more accurate if they're using those images. It's only the monster type brackets that I don't want to use images for for my cards.

**Comment by amarillonmc** [comment]
> Brackets

Your findings were spot-on.
But the thing is that you either would render the bracket from an image file or from the fonts.
if the former, you could edit/add the bracket by editing/adding the image, however, it's harder to do different size of brackets through font rendering since it essentally means that 2 different size properties are in the same field.

> What about using these images for Spell and Trap Cards? In my opinion, they look much more accurate if they're using those images. It's only the monster type brackets that I don't want to use images for for my cards.

Sorry I will need to decline this suggestion.
Because soon (after all the actual fixes are done), I'll continue adapt this template for custom card types.
Like, I could very well make a [Sound Stage] or [Spell Card (Duo-Icon)] (since they're mine and I know it's won'be changed), but it's a huge hassle for other card makers to create different image files, especially their custom mechanic are in need to change.

**Comment by Hello23-Ygopro** [comment]
> I could very well make a [Sound Stage] or [Spell Card (Duo-Icon)] (since they're mine and I know it's won'be changed), but it's a huge hassle for other card makers to create different image files, especially their custom mechanic are in need to change.

There's an option to enable and disable those images I referenced in Set Options, but they are definitely not needed, and in my opinion they require more work than it's worth in general, for an MSE aimed more towards fan-made cards, so I understand your decision.

Thanks for all the help! I'll let you know if I find any more issues.

I wish they would continue to work on MSE to perfect version 2.0.1. The only reason I'm using it over 2.0.0 is because it doesn't compress card art anymore.
Here are the main issues that I am/was concerned about going in version 2.0.1.:
☑ Fix color list
☐ Fix italic font
☑ Fix pendulum text to [not be italic by default](https://github.com/amarillonmc/MSE201_w_ygos10/blob/master/data/yugioh.mse-game/card_fields#L405) (doesn't have `flavor_text_filter(value)` anymore 👍)
☐ Fix monster brackets alignment
☑ Fix Link Rating font
