### ISSUE TITLE
[REQUEST] Series 11

### ISSUE THREAD

**Issue by LEO33SoFo** [amarillonmc/MSE201_w_ygos10#22]
Is there any plan to add support for _Series 11_ layout?

**Comment by amarillonmc** [comment]
Are there any notable differences between Series 10 and 11?
There were very notable differences between 9 and 10 to warrant a new template, but as for 10 to 11 most things are fine according to my other friends who are into PSD card making.

**Comment by LEO33SoFo** [comment]
According to [Yugipedia](https://yugipedia.com/wiki/Card_layout#Series_11_layout):
> - All card types now use a slightly paler shade of their previous background colors.
> - The [copyright notice](https://yugipedia.com/wiki/Copyright_notice) on the bottom-right corner of Japanese cards was changed from 「©高橋和希 スタジオ・ダイス／集英社」 (© [Kazuki Takahashi](https://yugipedia.com/wiki/Kazuki_Takahashi) - [Studio Dice](https://yugipedia.com/wiki/Studio_Dice)/[Shueisha](https://yugipedia.com/wiki/Shueisha)) to 「©スタジオ・ダイス／集英社・テレビ東京・ＫＯＮＡＭＩ」 (© Studio Dice/Shueisha, [TV Tokyo](https://yugipedia.com/wiki/TV_Tokyo), [Konami](https://yugipedia.com/wiki/Konami)). For TCG cards, it was similarly changed from "©1996 KAZUKI TAKAHASHI" to "©2020 Studio Dice/SHUEISHA, TV TOKYO, KONAMI".

So you may be right, perhaps it's not worth yet making a new template.

What about increasing the resolution of the template, from 421x614 to 813x1185 (350 pixels/inch) for better printing quality?

**Comment by amarillonmc** [comment]
Copyright notices can be changed manually in the template, and I'll say the paler shade is not because of a template change but of a print quality change.

Increasing the resolution is one thing I'll not do in this template, while I understand people may want to use my template to print out cards, ultimately it's not my intention for making this template, if you want better quality, you can run your exported images through a resize tool such like waifu2x, or use a PSD template.
