### ISSUE TITLE
Pendulum gold rare issue

### ISSUE THREAD

**Issue by marlleyilson** [amarillonmc/MSE201_w_ygos10#3]
![screenshot_5](https://user-images.githubusercontent.com/43358820/45775469-3e9c2600-bc26-11e8-895e-6462c67ad766.jpg)
![screenshot_6](https://user-images.githubusercontent.com/43358820/45775470-3e9c2600-bc26-11e8-8e38-86ecd85524b3.jpg)

yep, just after the fix of the missing gold rare border ;-;

**Comment by amarillonmc** [comment]
Aaaaaargh that's why I hate foils - too many if cases, I'll get to fix it right away.
====================
Should be fixed with the most recent commit.
feel free to reopen this if there's anything else that breaks.

**Comment by marlleyilson** [comment]
and something else broke, the ultimate rare foil
![screenshot_4](https://user-images.githubusercontent.com/43358820/45836184-7b2d5780-bce2-11e8-8b8e-3dc7559d7742.jpg)

same problem with the border and the foil is incomplete in pendulum cards
i got the earlier version (before the gold border fix) and it have this problem too

**Comment by amarillonmc** [comment]
*That*, was broke from the beginning.
I never received an Ultimate Rare foil for Pendulum Cards to begin with, (And since I never put foils on my own cards I never cared anyway.) you can check inside ``data\yugioh-series10.mse-style`` and you'll see there's not a foil texture for Ultimate Rare Pendulum Cards (there are for Gold Rare).
If you want to add them, you can add them with the following filenames:
``ultimatefoil-pendulum.png``
``ultimatefoil-pendulum-less.png``
``ultimatefoil-pendulum-more.png``

then do a pull request, I'll see what I can do.

**Comment by marlleyilson** [comment]
right. i'm working on it with the help of photoshop,trying to be most accurate as possible using the extended art foil as a base.
![ultimatefoil-pendulum](https://user-images.githubusercontent.com/43358820/45853857-0972ff00-bd1e-11e8-9f77-80a4b53c95b9.png)
later i'll make the less/more versions and fix the hologram. but now i'm confused, the pendulum text has foil or not?

**Comment by marlleyilson** [comment]
so, how i put them to work? i have no idea how to do it

**Comment by amarillonmc** [comment]
You need to declare it in the ``style`` file with if cases.
Refer to how things like gold rare pendulums are written.
